spring.application.name=tenancy-by-table
#
spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
#
spring.flyway.enabled=false
#
arconia.multitenancy.details.source=properties
arconia.multitenancy.details.tenants[0].identifier=tenant1
arconia.multitenancy.details.tenants[1].identifier=tenant2
#
arconia.multitenancy.resolution.http.header.header-name=x-tenant-id