spring.application.name=database-per-tenant
#
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
#
arconia.multitenancy.resolution.http.header.header-name=x-tenant-id

#arconia.multitenancy.details.source=properties
#
#arconia.multitenancy.details.tenants[0].identifier=0
#arconia.multitenancy.details.tenants[0].enabled=true
#arconia.multitenancy.details.tenants[0].attributes.tier=premium
#arconia.multitenancy.details.tenants[0].attributes.az=us-west-1
#
#arconia.multitenancy.details.tenants[1].identifier=1
#arconia.multitenancy.details.tenants[1].enabled=true
#arconia.multitenancy.details.tenants[1].attributes.tier=entry
#arconia.multitenancy.details.tenants[1].attributes.az=us-east-2