spring.application.name=service
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090
server.port=8081
spring.threads.virtual.enabled=true
#
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
#
#spring.flyway.table=service_flyway_schema_history
spring.flyway.enabled=false