spring.application.name=authorization-server
#
spring.threads.virtual.enabled=true
#
spring.security.oauth2.authorizationserver.client.spring.registration.client-id=spring
spring.security.oauth2.authorizationserver.client.spring.registration.client-secret={noop}spring
spring.security.oauth2.authorizationserver.client.spring.registration.client-authentication-methods[0]=client_secret_basic
spring.security.oauth2.authorizationserver.client.spring.registration.authorization-grant-types[0]=authorization_code
spring.security.oauth2.authorizationserver.client.spring.registration.authorization-grant-types[1]=client_credentials
spring.security.oauth2.authorizationserver.client.spring.registration.authorization-grant-types[2]=refresh_token
spring.security.oauth2.authorizationserver.client.spring.registration.authorization-grant-types[3]=urn:ietf:params:oauth:grant-type:device_code
spring.security.oauth2.authorizationserver.client.spring.registration.redirect-uris[0]=http://127.0.0.1:8080/login/oauth2/code/spring
spring.security.oauth2.authorizationserver.client.spring.registration.scopes[0]=openid
spring.security.oauth2.authorizationserver.client.spring.registration.scopes[1]=profile
spring.security.oauth2.authorizationserver.client.spring.registration.scopes[2]=email
spring.security.oauth2.authorizationserver.client.spring.registration.scopes[3]=user.write
spring.security.oauth2.authorizationserver.client.spring.registration.scopes[4]=user.read
#
server.port=9090
#
spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
#
