spring.application.name=schema-per-tenant
arconia.multitenancy.resolution.http.header.header-name=X-Tenant-Id

arconia.multitenancy.details.tenants[0].identifier=0
arconia.multitenancy.details.tenants[1].identifier=1
arconia.multitenancy.details.source=properties
spring.threads.virtual.enabled=true
